### ISSUE TITLE
Question: Suddenly getting pdftk executable not found errors.

### ISSUE THREAD

**Issue by jowilhnson** [MeteorPackaging/pdftk#8]
Year old project that relies heavily on PDFTK, has worked fine, now is suddenly saying it can't find the pdftk executable. 

pdftk --version returns "pdftk 2.02...." so it is definitely there. Is there some reason the pdftk:pdftk package would no longer be able to find the executable?

Fortunately this is only happening on my development system at the moment, but I am concerned about the production environment having the same problem at some point and our system becoming unusable. 

Development is on OSX 10.11, pdftk v2.02
Production is Ubuntu 12.10, pdftk v1.44

**Comment by aadamsx** [comment]
Well, it seems to me there must be some change on your system -- as this package hasn't changed.  That's the only reasonable explanation -- of course this doesn't help you.

What did you change recently?  Upgrade your system Mac (OS) lately?

**Comment by jowilhnson** [comment]
No changes that I can think of. But if your determination is that it's probably isolated to my system, I'll follow that theory and see if I can sort out why it can't find it on this machine. Sounds like in that case, it's unlikely to show the same behavior on our production server, so that's good news. Thanks!
